import {
  ArrowRight,
  Brain,
  Check,
  FileCheck2,
  ScanLine,
  Upload,
} from 'lucide-react'
import { Link } from 'react-router-dom'

const steps = [
  { icon: Upload, number: '01', title: 'Upload MRI', description: 'Select a brain MRI image in JPG or PNG format.' },
  { icon: ScanLine, number: '02', title: 'Image analysis', description: 'The submitted image is processed by the analysis service.' },
  { icon: Brain, number: '03', title: 'AI classification', description: 'Review the returned class and confidence scores.' },
  { icon: FileCheck2, number: '04', title: 'Generate report', description: 'Download the report generated by the backend.' },
]

const classes = ['Glioma', 'Meningioma', 'No Tumor', 'Pituitary']

export default function HomePage() {
  return (
    <>
      <section className="hero-section">
        <div className="page-container hero-grid">
          <div className="hero-copy">
            <span className="eyebrow"><span className="eyebrow-dot" /> MRI CLASSIFICATION SYSTEM</span>
            <h1>AI-Powered Brain Tumor Detection</h1>
            <p className="hero-description">
              Upload a brain MRI scan and receive an AI-based tumor classification with
              confidence scores and a downloadable diagnostic report.
            </p>
            <div className="hero-actions">
              <Link className="button button-primary" to="/analyze">
                Analyze MRI <ArrowRight size={17} />
              </Link>
              <Link className="button button-outline" to="/history">View History</Link>
            </div>
            <div className="hero-note"><Check size={15} /> Results come directly from the connected AI model</div>
          </div>

          <div className="hero-visual" aria-label="Abstract MRI analysis interface illustration">
            <div className="visual-grid" />
            <div className="visual-orbit orbit-one" />
            <div className="visual-orbit orbit-two" />
            <div className="visual-scan">
              <div className="scan-corner corner-top-left" />
              <div className="scan-corner corner-top-right" />
              <div className="scan-corner corner-bottom-left" />
              <div className="scan-corner corner-bottom-right" />
              <div className="scan-center"><Brain size={68} strokeWidth={1.1} /></div>
              <span className="scan-line" />
              <span className="scan-label">IMAGE ANALYSIS</span>
            </div>
            <div className="visual-chip chip-top"><Brain size={15} /> AI-assisted workflow</div>
            <div className="visual-chip chip-bottom"><ScanLine size={15} /> MRI classification</div>
            <span className="visual-coordinate coordinate-one">MRI · IMAGE ANALYSIS</span>
            <span className="visual-coordinate coordinate-two">CLASSIFICATION · 04 CLASSES</span>
          </div>
        </div>
      </section>

      <section className="section-block how-section">
        <div className="page-container">
          <div className="section-heading">
            <span className="eyebrow">A CLEAR, SIMPLE WORKFLOW</span>
            <h2>How It Works</h2>
            <p>From image upload to report download, every step is powered by the connected system.</p>
          </div>
          <div className="steps-grid">
            {steps.map(({ icon: Icon, number, title, description }) => (
              <article className="step-card" key={number}>
                <div className="step-card-top"><span className="step-icon"><Icon size={20} /></span><span>{number}</span></div>
                <h3>{title}</h3>
                <p>{description}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="section-block classes-section">
        <div className="page-container class-content">
          <div>
            <span className="eyebrow">SUPPORTED MRI CLASSIFICATION</span>
            <h2>Four model output classes</h2>
            <p>The interface displays the classes and scores returned by the prediction API.</p>
          </div>
          <div className="class-list">
            {classes.map((tumorClass, index) => (
              <div className="class-item" key={tumorClass}>
                <span className={`class-index class-index-${index + 1}`}>0{index + 1}</span>
                <span>{tumorClass}</span>
                <Check size={16} aria-hidden="true" />
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section-block model-section">
        <div className="page-container model-content">
          <div>
            <span className="eyebrow">AI / ML SYSTEM OVERVIEW</span>
            <h2>From MRI image to classification</h2>
            <p>A deep learning image classifier is accessed through the connected prediction API. No performance metrics are inferred by this interface.</p>
          </div>
          <div className="model-flow" aria-label="Image analysis process">
            {['MRI image', 'Preprocessing', 'Deep learning model', 'Classification', 'Confidence scores', 'Report'].map((step, index) => (
              <div className="model-flow-item" key={step}>
                <span>{String(index + 1).padStart(2, '0')}</span>
                <strong>{step}</strong>
                {index < 5 && <ArrowRight size={15} aria-hidden="true" />}
              </div>
            ))}
          </div>
          <dl className="model-facts">
            <div><dt>Model</dt><dd>Deep learning image classifier</dd></div>
            <div><dt>Input</dt><dd>Brain MRI image</dd></div>
            <div><dt>Output</dt><dd>4-class classification</dd></div>
            <div><dt>Inference</dt><dd>Prediction API</dd></div>
          </dl>
        </div>
      </section>

      <section className="disclaimer-section">
        <div className="page-container">
          <p><strong>Important:</strong> This system is an academic AI project intended for educational and demonstration purposes. It is not a substitute for professional medical diagnosis.</p>
        </div>
      </section>
    </>
  )
}
