"""PDF report generator for prediction results, using reportlab."""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_pdf_report(record: dict, output_path: str):
    doc = SimpleDocTemplate(output_path, pagesize=A4, topMargin=2 * cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#1e3a8a")
    )

    elements = []
    elements.append(Paragraph("Brain Tumor Detection - Report", title_style))
    elements.append(Spacer(1, 0.5 * cm))

    info_data = [
        ["Patient Name", record.get("patient_name", "Anonymous")],
        ["Report ID", str(record.get("id"))],
        ["Date", record.get("created_at", "")],
        ["Prediction", record.get("prediction", "")],
        ["Confidence", f"{record.get('confidence', 0):.2f}%"],
    ]
    info_table = Table(info_data, colWidths=[5 * cm, 10 * cm])
    info_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eff6ff")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(info_table)
    elements.append(Spacer(1, 1 * cm))

    elements.append(Paragraph("Class Probabilities", styles["Heading2"]))
    scores = record.get("all_scores", {})
    score_data = [["Tumor Type", "Confidence (%)"]] + [
        [k, f"{v:.2f}"] for k, v in scores.items()
    ]
    score_table = Table(score_data, colWidths=[7.5 * cm, 7.5 * cm])
    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a8a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(score_table)
    elements.append(Spacer(1, 1 * cm))

    disclaimer = (
        "Disclaimer: This report is generated by an AI model for educational/"
        "demonstration purposes only. It is NOT a medical diagnosis. Please "
        "consult a certified radiologist or physician for clinical decisions."
    )
    elements.append(Paragraph(disclaimer, styles["Italic"]))

    doc.build(elements)
